the-rooster/InstaTonne

InstaTonne/urls.py
InstaTonne/views.py

urls and views

---

InstaTonne-FrontEnd/package-lock.json
InstaTonneApis/endpoints/followers.py
InstaTonneApis/urls.py

closes #81
made delete put and get endpoints for followers. only works for local rn. will have to handle the follows relation differently once other nodes are brought into the mix.

Followers endpoints

---

InstaTonneApis/endpoints/inbox.py
InstaTonneApis/models.py

model fields got changed. fixed everything. should be working now with all examples in the spec!

fixed inbox endpoints

---

InstaTonne/urls.py
InstaTonneApis/endpoints/posts.py
InstaTonneApis/urls.py

create image endpoint and fix service path

---

InstaTonne-FrontEnd/package-lock.json
InstaTonne-FrontEnd/package.json
InstaTonne-FrontEnd/src/axiosCalls.ts
InstaTonneApis/endpoints/login.py
InstaTonneApis/endpoints/register.py

replaced redirects and renders in auth apis with http codes for the new front end!

auth apis just return http codes now

---

InstaTonne-FrontEnd/index.html
InstaTonne-FrontEnd/package-lock.json
InstaTonne-FrontEnd/src/App.vue
InstaTonne-FrontEnd/src/axiosCalls.ts
InstaTonne-FrontEnd/src/components/FollowRequests.vue
InstaTonne-FrontEnd/src/components/LoginPage.vue
InstaTonne-FrontEnd/src/components/PostEditor.vue
InstaTonne-FrontEnd/src/components/UserSearch.vue
InstaTonne/urls.py
InstaTonneApis/endpoints/login.py
InstaTonneApis/endpoints/posts.py

Basic login, no registration yet
the navigation drawer is still broken
the idea behind the login:
- we assume that the returned session deals with auth, and the authorid cookie is just to locally  tell us that we are logged in
- not sure if this is actually secure since we don't use a jwt
- this will work for basic account purposes for now, can fix it fully later

Login page

---

InstaTonneApis/models.py
InstaTonneApis/tests.py

Peep the comments in models.py

Model unittests

---

InstaTonne-FrontEnd/vue.config.ts
documentation/openapi.yml

Initial openAPI spec. Closes #110

Openapi spec

---

InstaTonne-FrontEnd/src/App.vue
InstaTonne-FrontEnd/src/components/UserPost.vue
InstaTonne-FrontEnd/src/main.ts

view public posts with a public url!

public posts

---

InstaTonne-FrontEnd/package-lock.json
InstaTonne-FrontEnd/src/components/AuthorCard.vue
InstaTonne-FrontEnd/src/components/ProfilePage.vue
InstaTonne-FrontEnd/src/components/UserSearch.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostFullCard.vue
InstaTonne-FrontEnd/src/main.ts
InstaTonne-FrontEnd/yarn.lock
InstaTonneApis/endpoints/inbox.py
InstaTonneApis/fixtures/initial_data.json

Profile page and user search page basically done. Profile page shows a grid of the authors posts, and queries the endpoints that logan is currently working on to retrieve local and or remote posts using the same api.
!!!

Browse public posts

---

InstaTonne-FrontEnd/yarn.lock
InstaTonneApis/endpoints/authors.py
InstaTonneApis/endpoints/comments.py
InstaTonneApis/endpoints/inbox.py
InstaTonneApis/endpoints/likes.py
InstaTonneApis/endpoints/posts.py
InstaTonneApis/endpoints/utils.py
InstaTonneApis/models.py
InstaTonneApis/urls.py

Comments and likes apis now match the other apis. Id's can be swapped with foreign urls. The only exception is in the get_single_comment and get_single_like endpoints, as those are purely for returning resources in the inbox when comments and likes are made.
API should be complete now, but this will likely require some testing.

Comments and likes with inbox

---

InstaTonne-FrontEnd/src/components/EditPostPage.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostFullCard.vue
InstaTonneApis/endpoints/posts.py

Tested this by sharing a post through the UI. Looks like it works. It will make a new post for that new Author (the id_url will include the id of the most recently shared-from Author) but with all the information from the previous post except for Source is changed.

#147 share post

---

InstaTonne-FrontEnd/src/App.vue
InstaTonne-FrontEnd/src/main.ts
InstaTonneApis/endpoints/utils.py

Small PR to always check for the id cookie.
We can't check for the session cookie on the frontend since that cookie is httpOnly; we have to assume that it is there. 
The utils.py change is only because my python version complains and won't let me compile if it's there (I am tired of manually deleting it all the time)

Made vue-router check for userCookie on every page, added logout button.

---

InstaTonne-FrontEnd/package.json
InstaTonne-FrontEnd/src/axiosCalls.ts
InstaTonne-FrontEnd/src/components/EditProfilePage.vue
InstaTonne-FrontEnd/src/components/ProfilePage.vue
InstaTonne-FrontEnd/src/components/UserPost.vue
InstaTonne-FrontEnd/src/components/stream_cards/CommentCard.vue
InstaTonne-FrontEnd/src/components/stream_cards/InboxCommentCard.vue
InstaTonne-FrontEnd/src/components/stream_cards/InboxLikeCard.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostFullCard.vue
InstaTonne-FrontEnd/src/main.ts
InstaTonne-FrontEnd/vite.config.ts
InstaTonne/settings.py
InstaTonne/urls.py
InstaTonne/views.py
InstaTonneApis/endpoints/utils.py

Actually prepped for deployment. will make prod branch next for heroku!

Real prep time

---

InstaTonne-FrontEnd/yarn.lock
InstaTonneApis/endpoints/comments.py
InstaTonneApis/endpoints/inbox.py
InstaTonneApis/endpoints/likes.py
InstaTonneApis/models.py
InstaTonneApis/urls.py

Still have some 401s and 400s for posts being returned. Will investigate further, but wanted this up for now
Closes #180, Closes #181, Closes #182

Some more swagger stuff

---

InstaTonne/settings.py
InstaTonneApis/adapters/adapters.py
InstaTonneApis/adapters/group20.py
InstaTonneApis/endpoints/posts.py

Added headers to CORS_ALLOW_HEADERS that need to be there. 
Beginning to write adapters for other groups that do weird stuff

Fixing cors

---

InstaTonneApis/adapters/group20.py

adapter working for group20

---

InstaTonneApis/adapters/adapters.py
InstaTonneApis/adapters/group20.py
InstaTonneApis/endpoints/posts.py

adapters all the way

---

InstaTonne-FrontEnd/src/components/AboutPage.vue
InstaTonne-FrontEnd/src/components/UserSearch.vue
InstaTonne-FrontEnd/src/components/stream_cards/CommentCard.vue

Fixed the issue where the author name was always the signed in user

Comment card name fixed

---

InstaTonne-FrontEnd/src/components/AboutPage.vue
InstaTonne-FrontEnd/src/components/HomePage.vue
InstaTonne-FrontEnd/src/components/PostEditor.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostFullCard.vue

Fixed some UI oddities, reversed inbox to show newest posts first, added back edit and delete post buttons,
Closes #197

UI improvements and Edit and Delete post is back on my posts

---

InstaTonneApis/endpoints/register.py

changed the default profile image to some guy

change default profile image

---

InstaTonne-FrontEnd/index.html
InstaTonne-FrontEnd/src/components/PostEditor.vue
InstaTonne-FrontEnd/src/components/stream_cards/InboxCommentCard.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostFullCard.vue
InstaTonne-FrontEnd/src/style.css

cleaning up the UI and fixing some buggy css

Fixing css

---

InstaTonneApis/endpoints/authors.py
InstaTonneApis/endpoints/comments.py
InstaTonneApis/endpoints/followers.py
InstaTonneApis/endpoints/likes.py
InstaTonneApis/endpoints/posts.py

Shouldn't change anything, just doc improvements.

Just refined swagger docs

---

InstaTonne-FrontEnd/src/components/UserSearch.vue
InstaTonneApis/endpoints/authors.py

User search page actually uses paging now. fixed url query params not being sent to server properly.

fixed user search page

---

InstaTonne-FrontEnd/index.html
InstaTonne-FrontEnd/src/components/FriendsPage.vue
InstaTonne-FrontEnd/src/components/stream_cards/FollowRequestCard.vue
InstaTonne-FrontEnd/src/components/stream_cards/FriendCard.vue
InstaTonneApis/endpoints/followers.py

Refactored the friend page to have links to followers profiles.
Also added a remove follower button.
Added CSS to make it look better (but not that much better, im bad at graphic design).
Fixed a bug with the followers api to only look at accepted follows

Refactored friends page

---

InstaTonneApis/endpoints/authors.py
InstaTonneApis/endpoints/github.py
InstaTonneApis/endpoints/inbox.py
InstaTonneApis/endpoints/likes.py
InstaTonneApis/endpoints/posts.py
InstaTonneApis/models.py
InstaTonneApis/urls.py

making a new inbox endpoint that gets the normal inbox stuff plus the github stuff

create ginbox endpoint

---

InstaTonneApis/adapters/adapters.py
InstaTonneApis/adapters/group2.py
InstaTonneApis/endpoints/comments.py

Adapters for getting comments properly from group2

Group2adapters

---

InstaTonne-FrontEnd/src/components/ProfilePage.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostPreviewCard.vue
InstaTonneApis/endpoints/followers.py

Profile grid now fixed.
Adapters for group 2 working>???????!?1//!?

fixed grid + fixed adapters for group 2

---

InstaTonne-FrontEnd/src/components/HomePage.vue
InstaTonne-FrontEnd/src/components/stream_cards/GithubCard.vue
InstaTonne-FrontEnd/src/components/stream_cards/PostFullCard.vue
InstaTonne/settings.py

Github events now show up in your stream. can be enabled / disabled

GITHUB EVENTS

---

InstaTonne-FrontEnd/src/components/HomePage.vue

Was getting this error, `TypeError: Cannot read properties of undefined (reading 'toLowerCase')`
The changes work for me now. Tested on prod and on main and worked on both

Fixed stream not showing anything since toLowerCase wasn't working
